#############################################################################
# Makefile for building: Scraping
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  Scraping.pro
# Template: app
# Command: /home/rb/devel/SDK/Qt/5.11.2/gcc_64/bin/qmake -o Makefile Scraping.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/libxml2 -isystem /usr/include/curl -I../../../../SDK/Qt/5.11.2/gcc_64/include -I../../../../SDK/Qt/5.11.2/gcc_64/include/QtCore -I. -I../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/rb/devel/SDK/Qt/5.11.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/rb/devel/SDK/Qt/5.11.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/rb/devel/SDK/Qt/5.11.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Scraping1.0.0
DISTDIR = /home/rb/devel/projects/c++/Scraping/Scraping/.tmp/Scraping1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/rb/devel/SDK/Qt/5.11.2/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/rb/devel/projects/c++/Scraping/Scraping/../../../../../../../usr/lib/x86_64-linux-gnu/ -lxml2 -lcurl -L/home/rb/devel/SDK/Qt/5.11.2/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		scraper.cpp 
OBJECTS       = main.o \
		scraper.o
DIST          = ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf \
		Scraping.pro scraper.h main.cpp \
		scraper.cpp
QMAKE_TARGET  = Scraping
DESTDIR       = 
TARGET        = Scraping


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Scraping.pro ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf \
		Scraping.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Scraping.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_pre.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/unix.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/linux.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/sanitize.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-base.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/common/g++-unix.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/qconfig.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_functions.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt_config.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/toolchain.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_pre.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resolve_config.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/default_post.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qml_debug.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/warn_on.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qt.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/resources.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/moc.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/unix/thread.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/qmake_use.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/file_copies.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/exceptions.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/yacc.prf:
../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/lex.prf:
Scraping.pro:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Scraping.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents scraper.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp scraper.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../../SDK/Qt/5.11.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp scraper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

scraper.o: scraper.cpp scraper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scraper.o scraper.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Scraping/bin || mkdir -p $(INSTALL_ROOT)/opt/Scraping/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Scraping/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Scraping/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Scraping/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

